### ISSUE TITLE
 toggleButtonPos: 'bottom-right',无效

### ISSUE THREAD

**Issue by 1710929851** [hellof2e/click-to-vue-component#3]
![image](https://github.com/user-attachments/assets/c072727d-c4ad-404f-8538-a454cea9b265)
    vitePlugins.push(
      inspector({
        toggleButtonPos: 'bottom-right',
      }),
    );
图标位置还是在右上角

**Comment by 1710929851** [comment]
版本信息:
vite:4.40,
vue:3.34,

**Comment by xxxsf** [comment]
移除了 toggleButtonPos，图标改为可以拖拽的方式了。此外可以通过
```ts
inspector({
  toggleButtonVisibility: 'never'
})
```
隐藏图标

还可以直接用快捷键
```ts
Mac: Command(⌘) + Shift(⇧)
Windows: Ctrl + Shift(⇧) 
```
唤起
